/**
 * Blog index used by the /blogs listing + date-archive routes. Posts themselves
 * are served as legacy pages by the catch-all; these routes just list them so the
 * old /blogs, /blogs/{year}, and /blogs/{year}/{month} listing URLs resolve (200)
 * instead of 404-ing at cutover. Category URLs are 301'd to /blogs in next.config.
 */
import posts from './blog-index.json'

export interface BlogPost {
  path: string
  title: string
  year: string
  month: string
  monthIdx: number
}

const POSTS = posts as BlogPost[]

export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

export function years(): string[] {
  return [...new Set(POSTS.map((p) => p.year))]
}
export function postsByYear(year: string): BlogPost[] {
  return POSTS.filter((p) => p.year === year)
}
export function postsByYearMonth(year: string, month: string): BlogPost[] {
  return POSTS.filter((p) => p.year === year && p.month === month)
}
export function yearMonths(): { year: string; month: string }[] {
  const seen = new Set<string>()
  const out: { year: string; month: string }[] = []
  for (const p of POSTS) {
    const k = `${p.year}/${p.month}`
    if (!seen.has(k)) { seen.add(k); out.push({ year: p.year, month: p.month }) }
  }
  return out
}

import legacyPages from './legacy-pages.json'

const MONTHS_FULL = ['January','February','March','April','May','June','July','August','September','October','November','December']
const pageBody = (path: string): string => ((legacyPages as Record<string, { body?: string }>)[path]?.body) ?? ''

export interface DatedBlogPost extends BlogPost { date: string; ts: number }

function postDate(p: BlogPost): { date: string; ts: number } {
  const m = pageBody(p.path).slice(0, 500).match(/(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(20\d\d)/)
  if (m) {
    const mi = MONTHS_FULL.indexOf(m[1])
    return { date: `${m[1]} ${Number(m[2])}, ${m[3]}`, ts: Date.UTC(Number(m[3]), mi, Number(m[2])) }
  }
  return { date: `${cap(p.month)} ${p.year}`, ts: Date.UTC(Number(p.year), p.monthIdx, 1) }
}

let _sorted: DatedBlogPost[] | null = null
export function allPostsSorted(): DatedBlogPost[] {
  if (!_sorted) _sorted = POSTS.map((p) => ({ ...p, ...postDate(p) })).sort((a, b) => b.ts - a.ts)
  return _sorted
}

// ── Per-post metadata (date / author / categories / image), normalized via the
// owner-approved author + category maps (generated by scripts/build-blog-meta.mjs). ──
import blogMetaJson from './blog-meta.json'
import blogCategoriesJson from './blog-categories.json'

export interface BlogCategory { slug: string; name: string; count: number }
export interface BlogMeta { date: string; author: string; categories: { slug: string; name: string }[]; image: string | null; ogImage: string | null }

const META = blogMetaJson as Record<string, BlogMeta>
const CATEGORIES = blogCategoriesJson as BlogCategory[]

export function blogMeta(path: string): BlogMeta {
  return META[path.replace(/\/+$/, '')] ?? { date: '', author: 'Crain & Wooley', categories: [], image: null, ogImage: null }
}
export function allCategories(): BlogCategory[] { return CATEGORIES }
export function categoryBySlug(slug: string): BlogCategory | undefined { return CATEGORIES.find((c) => c.slug === slug) }

export function postsByCategory(slug: string): DatedBlogPost[] {
  return allPostsSorted().filter((p) => blogMeta(p.path).categories.some((c) => c.slug === slug))
}

/** Related = most-recent other posts sharing any category; pads with recents to `n`. */
export function relatedPosts(path: string, n = 4): DatedBlogPost[] {
  const norm = path.replace(/\/+$/, '')
  const mine = new Set(blogMeta(norm).categories.map((c) => c.slug))
  const sorted = allPostsSorted().filter((p) => p.path !== norm)
  const sameCat = mine.size ? sorted.filter((p) => blogMeta(p.path).categories.some((c) => mine.has(c.slug))) : []
  const out = [...sameCat]
  for (const p of sorted) { if (out.length >= n) break; if (!out.includes(p)) out.push(p) }
  return out.slice(0, n)
}

/** Newer/older neighbours in the global date-sorted order (for prev/next nav). */
export function adjacentPosts(path: string): { newer: DatedBlogPost | null; older: DatedBlogPost | null } {
  const sorted = allPostsSorted()
  const i = sorted.findIndex((p) => p.path === path.replace(/\/+$/, ''))
  if (i < 0) return { newer: null, older: null }
  return { newer: i > 0 ? sorted[i - 1] : null, older: i < sorted.length - 1 ? sorted[i + 1] : null }
}
